# NumPy Inventory System

## Problem

A retail warehouse needs to manage inventory across multiple storage bins. Currently, they use Python lists and manual calculations, which is slow and error-prone.

Your task is to build a NumPy-based system that can:
1. Create and organize inventory data as NumPy arrays
2. Perform calculations (totals, averages, value)
3. Reshape and filter data to identify low-stock products
4. Generate reports with key statistics

### Real-World Context

Imagine you're the warehouse manager. Every morning, your team scans stock levels in 4 storage bins for 3 different products. Instead of writing down numbers on paper and using a calculator, you want a system that instantly tells you:
- How much total stock we have for each product
- Which products are running dangerously low
- The total value of inventory

NumPy arrays make this fast and reliable. A single operation on an array of 1 million items runs in milliseconds, while a Python loop would take seconds.

### Why NumPy?

- **Speed:** NumPy operations are implemented in C and run 10–100× faster than Python loops
- **Memory:** Arrays use less memory than lists
- **Readability:** `array.sum()` is clearer than `sum(my_list)`
- **Broadcasting:** Perform operations on entire arrays without explicit loops

In [ ]:
import numpy as np
import pandas as pd

## Task 1: Create and Reshape Inventory Arrays

**Goal:** Write a function that takes a flat list of stock counts and reshapes it into a 2D array (products × bins).

**Input:** A flat list of integers (stock counts)
**Output:** A 2D NumPy array with shape (num_products, num_bins)

**Example:**
```
Input: [5, 3, 8, 2, 7, 4, 6, 1, 9, 2, 5, 3]
Output shape: (3, 4)  # 3 products, 4 bins each
Output array:
[[5 3 8 2]
 [7 4 6 1]
 [9 2 5 3]]
```

In [ ]:
def create_inventory_array(stock_list, num_products):
    """
    Create a 2D inventory array from a flat list of stock counts.
    
    Args:
        stock_list: A flat list of integers representing stock counts
        num_products: Number of products (rows in the output array)
    
    Returns:
        A 2D NumPy array with shape (num_products, num_bins)
    """
    pass

## Task 2: Calculate Stock Metrics

**Goal:** Write a function that computes key inventory statistics from a 2D array.

**Input:** A 2D inventory array (products × bins) and a price list (price per product)
**Output:** A dictionary with three keys:
- `'total_stock'`: Total units per product (sum across bins)
- `'avg_stock'`: Average units per product (mean across bins)
- `'inventory_value'`: Total value per product (total_stock × price)

**Example:**
```
Input array:
[[5 3 8 2]
 [7 4 6 1]
 [9 2 5 3]]

Prices: [10.0, 15.0, 20.0]

Output:
{'total_stock': array([18, 18, 19]),
 'avg_stock': array([4.5, 4.5, 4.75]),
 'inventory_value': array([180., 270., 380.])}
```

In [ ]:
def calculate_metrics(inventory_array, prices):
    """
    Calculate inventory metrics from a 2D array.
    
    Args:
        inventory_array: A 2D NumPy array (products × bins)
        prices: A list or array of prices (one per product)
    
    Returns:
        A dictionary with keys 'total_stock', 'avg_stock', 'inventory_value'
    """
    pass

## Task 3: Identify Low-Stock Products

**Goal:** Write a function that finds products with any bin below a stock threshold.

**Input:** A 2D inventory array and a threshold value
**Output:** A dictionary with two keys:
- `'low_stock_indices'`: Indices of products with at least one bin below threshold
- `'low_stock_counts'`: Count of bins below threshold for each low-stock product

**Example:**
```
Input array:
[[5 3 8 2]
 [7 4 6 1]
 [9 2 5 3]]

Threshold: 5

Output:
{'low_stock_indices': array([0, 1, 2]),
 'low_stock_counts': array([3, 2, 2])}
```

(Product 0 has 3 bins below 5: [3, 2, 2]; Product 1 has 2 bins below 5: [4, 1]; Product 2 has 2 bins below 5: [2, 3])

In [ ]:
def find_low_stock(inventory_array, threshold):
    """
    Find products with bins below a stock threshold.
    
    Args:
        inventory_array: A 2D NumPy array (products × bins)
        threshold: Minimum stock level per bin
    
    Returns:
        A dictionary with keys 'low_stock_indices' and 'low_stock_counts'
    """
    pass

## Task 4: Generate Inventory Report

**Goal:** Write a function that creates a summary report as a pandas DataFrame.

**Input:** A 2D inventory array, product names, and prices
**Output:** A pandas DataFrame with columns:
- `'Product'`: Product name
- `'Total Stock'`: Total units (sum across bins)
- `'Avg Stock'`: Average units per bin
- `'Price'`: Unit price
- `'Inventory Value'`: Total stock × price

**Example:**
```
Input:
Array: [[5 3 8 2] [7 4 6 1] [9 2 5 3]]
Products: ['Widget A', 'Widget B', 'Widget C']
Prices: [10.0, 15.0, 20.0]

Output DataFrame:
     Product  Total Stock  Avg Stock  Price  Inventory Value
0  Widget A            18        4.5   10.0            180.0
1  Widget B            18        4.5   15.0            270.0
2  Widget C            19       4.75   20.0            380.0
```

In [ ]:
def generate_report(inventory_array, product_names, prices):
    """
    Generate an inventory report as a pandas DataFrame.
    
    Args:
        inventory_array: A 2D NumPy array (products × bins)
        product_names: A list of product names
        prices: A list of prices (one per product)
    
    Returns:
        A pandas DataFrame with columns: Product, Total Stock, Avg Stock, Price, Inventory Value
    """
    pass

## Test Your Implementation

Run the cells below to verify your functions work correctly.

In [ ]:
# Test Task 1
stock_list = [5, 3, 8, 2, 7, 4, 6, 1, 9, 2, 5, 3]
array_1 = create_inventory_array(stock_list, 3)
print('Task 1: Create and Reshape')print('Shape:', array_1.shape)
print('Array:\n', array_1)


In [ ]:
# Test Task 2
prices = [10.0, 15.0, 20.0]
metrics = calculate_metrics(array_1, prices)
print('Task 2: Calculate Metrics')
print('Total Stock:', metrics['total_stock'])
print('Avg Stock:', metrics['avg_stock'])
print('Inventory Value:', metrics['inventory_value'])


In [ ]:
# Test Task 3
low_stock = find_low_stock(array_1, 5)
print('Task 3: Find Low-Stock Products')
print('Low-stock indices:', low_stock['low_stock_indices'])
print('Low-stock counts:', low_stock['low_stock_counts'])


In [ ]:
# Test Task 4
product_names = ['Widget A', 'Widget B', 'Widget C']
report = generate_report(array_1, product_names, prices)
print('Task 4: Generate Report')
print(report)
